FROM nginx
USER root

COPY main.c .
COPY nginx/nginx.conf ./nginx/nginx.conf
COPY run_server.sh .

RUN apt update && apt install -y gcc spawn-fcgi libfcgi-dev && chmod 777 ./run_server.sh

CMD ["sh", "./run_server.sh"]